### ISSUE TITLE
Request help

### ISSUE THREAD

**Issue by oKexin** [DoranLyong/Shape_from_Focus#1]
Hello, your 'shape from focus' Repository gave me great help. Do you have the ground truth of the data cone? Your Repository just give the source image. I would appreciate it if you could upload the ground truth data or tell me how to generate it. My email is kexinchen_bjut@163.com. Thank you!

**Comment by DoranLyong** [comment]
@1084068438  Hi, thanks for your interest.  
Unfortunately, it was old work and there is no remaining source for me.   

I attach a link to generate some synthetic defocus image sequences. 
- https://kr.mathworks.com/matlabcentral/fileexchange/55095-defocus-simulation

I hope it could be help.
